/**
 * @file ADC_cfg.h
 * @author G3_DashBoard_Team
 * @brief Configuration file for ADC driver for stm32f401cc
 * @version 0.1
 * @date 2023-02-24
 * 
 * @copyright Copyright (c) 2023
 * 
 */

#ifndef ADC_CFG_H
#define ADC_CFG_H




#define ADC_CONVERSION         ADC_ENABLE
#define ADC_RESOLUTION         ADC_RESOLUTION_10BIT
#define ADC_SCAN_MODE          ADC_ENABLE
#define ADC_DATAD_ALLIGNMENT   ADC_RIGHT_ALLIGNMENT
#define ADC_EOC_SELECTION      ADC_AFTER_EACH_CONVERSION
#define ADC_DMA_SELSCTION      ADC_DMA_FREE_RUNNING_COPY
#define ADC_DMA_MODE           ADC_ENABLE
#define ADC_EOC_INT            ADC_DISABLE
#define ADC_CONVERSION_MODE    ADC_CONTINOUS

#define ADC_REGULAR_SEG_CHANNELS_LENGHT   3

#define ADC_CHANELL_0_SAMPLE_TIME   ADC_SAMPLE_3_CYCLES
#define ADC_CHANELL_1_SAMPLE_TIME   ADC_SAMPLE_3_CYCLES
#define ADC_CHANELL_2_SAMPLE_TIME   ADC_SAMPLE_3_CYCLES
#define ADC_CHANELL_3_SAMPLE_TIME   ADC_SAMPLE_3_CYCLES
#define ADC_CHANELL_4_SAMPLE_TIME   ADC_SAMPLE_3_CYCLES
#define ADC_CHANELL_5_SAMPLE_TIME   ADC_SAMPLE_3_CYCLES
#define ADC_CHANELL_6_SAMPLE_TIME   ADC_SAMPLE_3_CYCLES
#define ADC_CHANELL_7_SAMPLE_TIME   ADC_SAMPLE_3_CYCLES


#define ADC_REGULAR_SEQ_1  ADC_CHANELL_0
#define ADC_REGULAR_SEQ_2  ADC_CHANELL_4
#define ADC_REGULAR_SEQ_3  ADC_CHANELL_3
#define ADC_REGULAR_SEQ_4  ADC_CHANELL_0
#define ADC_REGULAR_SEQ_5  ADC_CHANELL_0
#define ADC_REGULAR_SEQ_6  ADC_CHANELL_0
#define ADC_REGULAR_SEQ_7  ADC_CHANELL_0


#define ADC_ANALOG_WTD_REG             ADC_DISABLE
#define ADC_ANALOG_WTD_INJ             ADC_DISABLE
#define ADC_OVERRUN_INT                ADC_DISABLE
#define ADC_DISCONTENOUS_MODE_REG      ADC_DISABLE
#define ADC_DISCONTENOUS_MODE_INJ      ADC_DISABLE
#define ADC_AUTOMATIC_INJ_CONVERSION   ADC_DISABLE
#define ADC_INJ_CHANNELS_INT           ADC_DISABLE
#define ADCANALOG_WTD_INT              ADC_DISABLE
#define ADC_EOC_INT                    ADC_DISABLE





#endif
